Repository nathan-weinberg/jeeves, pull requests merged in 2020-07, with the labels that each got.

#135 Fixing CI issues
  .github/workflows/flake8.yml
  .github/workflows/pytest.yml
  config.yaml.example
  requirements.txt
Labels: WIP, test

#137 Allow search filter using regex
  config.yaml.example
  docs/README.md
  functions.py
Labels: WIP

#147 Add pie chart to the email report
  report.py
  templates/report_template.html
Labels: RFE
